system_packages = [
  { name = "zsh", package_manager = "pacman" },
  { name = "niri", package_manager = "pacman" },
  { name = "waybar", package_manager = "pacman" },
  { name = "swaylock-effects", package_manager = "yay" },
  { name = "neovim", package_manager = "pacman" },
  { name = "wofi", package_manager = "pacman" },
  { name = "kitty", package_manager = "pacman" },
  { name = "zen-browser-bin", package_manager = "yay" },
  { name = "zoxide", package_manager = "pacman" },
  { name = "fzf", package_manager = "pacman" },
  { name = "eza", package_manager = "pacman" },
  { name = "git", package_manager = "pacman" },
  { name = "bat", package_manager = "pacman" },
  { name = "ripgrep", package_manager = "pacman" },
  { name = "stow", package_manager = "pacman" },
  { name = "xwayland-satellite", package_manager = "pacman" },
  { name = "awww", package_manager = "pacman" },
  { name = "power-profiles-daemon", package_manager = "pacman" },
  { name = "nmrs", package_manager = "pacman" },
  { name = "playerctl", package_manager = "yay" },
  { name = "python-setuptools", package_manager = "yay" },
  { name = "zscroll", package_manager = "yay" },
]
